services:
  mongo:
    image: mongo:7
    container_name: assignment-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: assignment-backend
    restart: unless-stopped
    depends_on:
      - mongo
    environment:
      PORT: 5000
      MONGO_URI: mongodb://mongo:27017/intern_assignment
      JWT_SECRET: docker_change_me
      JWT_EXPIRES_IN: 1d
      CORS_ORIGIN: http://localhost:5173
    ports:
      - "5000:5000"

  frontend:
    build: ./frontend
    container_name: assignment-frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "5173:5173"

volumes:
  mongo_data:
